apiVersion: v1
kind: Service
metadata:
  name: sqlapp-service # we create this service and call this service since for ingress, we need a service
  namespace: namesqlapp
spec:
  selector:
    app: my-sqlapp  # This should match the label of your pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # The port your application is listening on
