apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-pvc
spec:
  storageClass: "manual"
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
