apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: default
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  hostPath:
    path: {{ .Values.persistentVolume.path }}
