apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  hostPath:
    path: {{ .Values.persistentVolume.path }}
