apiVersion: v1
kind: Service
metadata:
  name: {{ include "eksqlchart.fullname" . }}
  namespace: namesqlapp2
spec:
  selector:
    app: my-sqlapp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
