# name : Build and Push Docker image to Docker Hub 

# on: 
#   push:
#     branches:
#       - main
# jobs:
#   push_to_registry:
#     name: Push Docker image to Docker Hub
#     runs-on: macos-latest
#     steps:
#       - run: |
#           brew install docker 
#           colima start 
#           docker run -p 3306:3000
      
#       - name: Check out the repo 
#         uses: actions/checkout@v3

#       # - name: Set up QEMU
#       #   uses: docker/setup-qemu-action@v3

#       - name: Set up Docker Context for Buildx
#         id: buildx-context
#         run: |
#           docker context create builders
       
#       - name: Set up Docker Buildx
#         id: buildx
#         uses: docker/setup-buildx-action@v3
#         with:
#           version: latest 
#           endpoint : builders

#       - name: Login to Docker Hub 
#         uses: docker/login-action@v3 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
         
#       - name: Build and push 
#         uses:  docker/build-push-action@v5
#         with:
#           file: Dockerfile
#           context: .
#           platforms: linux/amd64,linux/arm64
#           push: true
#           tags: ekhari/dockergitsql:latest
name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ekhari/dockergitsql:latest .
          docker push ekhari/dockergitsql:latest
